# Generated by Django 4.2.1 on 2023-05-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Members',
        ),
    ]
